name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution (.sln) file relative to the root of the project.
  SOLUTION_FILE_PATH: Source/KDU.sln

  # Configuration type to build (e.g., Release or Debug).
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the code from the repository
    - uses: actions/checkout@v4

    # Add MSBuild to PATH
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore NuGet packages
    - name: Restore NuGet packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    # Build the solution
    - name: Build
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    # Upload the compiled files as artifacts
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Build-Artifacts
        path: ${{env.GITHUB_WORKSPACE}}/bin/${{env.BUILD_CONFIGURATION}}
